---
- name: Comprehensive Network Device Health Check
  hosts: all
  gather_facts: no

  vars:
    critical_cpu_threshold: 80
    critical_memory_threshold: 85

  tasks:
    - name: Collect system information
      cisco.ios.ios_command:
        commands:
          - show version | include Software
          - show version | include uptime
          - show processes cpu sorted | include CPU
          - show memory statistics | include Processor
      register: system_info

    - name: Parse and display CPU usage
      debug:
        msg: 
          - "Device: {{ inventory_hostname }}"
          - "Software: {{ system_info.stdout_lines[0][0] }}"
          - "Uptime: {{ system_info.stdout_lines[1][0] }}"
          - "CPU: {{ system_info.stdout_lines[2][0] }}"
          - "Memory: {{ system_info.stdout_lines[3][0] }}"

    - name: Check for high CPU usage
      fail:
        msg: "CRITICAL: CPU usage above {{ critical_cpu_threshold }}%"
      when: (system_info.stdout_lines[2][0] | regex_search('\\d+%')) | int > critical_cpu_threshold

    - name: Get interface status
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
        when: inventory_hostname in groups['routers']
      
          - show interfaces status
        when: inventory_hostname in groups['switches']
      register: interface_status

    - name: Display interface summary
      debug:
        msg: "{{ interface_status.stdout_lines }}"