---
- name: Collect Basic Device Information
  hosts: routers,switches
  gather_facts: no

  tasks:
    - name: Show device version
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

    - name: Display version information
      debug:
        msg: "{{ version_output.stdout_lines }}"

    - name: Show running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Save running config to file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "./config_backups/{{ inventory_hostname }}_config_{{ ansible_date_time.date }}.txt"