---
- name: Update Device User Accounts
  hosts: all
  gather_facts: no

  tasks:
    - name: Add new user account
      cisco.ios.ios_user:
        aggregate:
          - name: admin
            privilege: 15
            configured_password: "admin123"
            password_type: secret  # Type 5 (MD5) password
            state: present
          - name: network_operator
            privilege: 1
            configured_password: "operator123"
            password_type: secret  # Type 5 (MD5) password
            state: present
        state: present
        update_password: always  # အမြဲ password update လုပ်မယ်

    - name: Show local users
      cisco.ios.ios_command:
        commands:
          - show running-config | include username
      register: user_info

    - name: Display user accounts
      debug:
        msg: "{{ user_info.stdout_lines }}"